version: '3.8'

services:
  # Development service with hot reload
  elysia-dev:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_KEY=${API_KEY}
    profiles:
      - dev

  # Production service
  elysia-prod:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
    restart: unless-stopped
    profiles:
      - prod

  # Alternative production service with custom port
  elysia-server:
    build:
      context: .
      target: production
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_KEY=${API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
